POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"Monyet Damm",
    "nim":"3434232",
    "image_profile":"fsdfede",
    "division": "Multimedia",
    "password": "sdsafdaf",
    "role": "admin",
    "email": "gabriell@gmail.com",
    "number_phone": "0895622060619"
}

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"gabriel@gmail.com",
    "password": "sdsafdaf"
}

# "email":"gabriell@gmail.com",
#     "password": "sdsafdaf"