GET http://localhost:3000/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsbEBnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJhZG1pbiIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk4MDM3Njg0fQ.GDTjwUHnP41NStO9r6EiJ_7J7ViCuXLcXbsRqig_O1A

###
POST http://localhost:3000/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsbEBnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJhZG1pbiIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk3ODc3Mjk2fQ.gbNXLSIKyxH5sASc3nW97p-x062sl5hsizqCBVVGAEg

{
    "user_id": 1,
    "title": "Belajar Interface di GO",
    "materi": "Bukan Lorem",
    "link_video": "https://youtu.be/jPjPGAQOMac?si=TyifhR_oVn2nEJ8d",
    "division": "Multimedia",
    "playlist": "Dasar Golang",
    "slug": "belajar-interface-di-go",
    "category": "backend",
    "image_course": "dsad"
}

###
PUT http://localhost:3000/courses/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsbEBnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJhZG1pbiIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk4MDM3Njg0fQ.GDTjwUHnP41NStO9r6EiJ_7J7ViCuXLcXbsRqig_O1A

{
    "user_id": 1,
    "title": "Belajar Interface di GO Sip",
    "materi": "Bukan Lorem",
    "link_video": "https://youtu.be/jPjPGAQOMac?si=TyifhR_oVn2nEJ8d",
    "division": "Multimedia",
    "playlist": "Dasar Golang",
    "slug": "belajar-interface-di-go",
    "category": "backend",
    "image_course": "dsad"
}

###
GET http://localhost:3000/courses/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsbEBnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJhZG1pbiIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk4MDM3Njg0fQ.GDTjwUHnP41NStO9r6EiJ_7J7ViCuXLcXbsRqig_O1A

###
DELETE  http://localhost:3000/courses/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsbEBnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJhZG1pbiIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk4MDM3Njg0fQ.GDTjwUHnP41NStO9r6EiJ_7J7ViCuXLcXbsRqig_O1A
