GET http://localhost:3000/users
Content-Type: application/json

###
POST  http://localhost:3000/users
Content-Type: application/json

{
    "name":"Monyet Ksnandar",
    "nim":"3434232",
    "image_profile":"fsdfede",
    "division": "Multimedia",
    "email": "gabriel@gmail.com",
    "number_phone": "0895622060619"
}

###
GET http://localhost:3000/users/6
Content-Type: application/json

###
PUT  http://localhost:3000/users/5
Content-Type: application/json

{
    "name":"Monyet Cuki Cuki",
    "nim":"3434232",
    "image_profile":"fsdfede",
    "division": "Multimedia",
    "email": "gabriel@gmail.com",
    "number_phone": "0895622060619"
}

###
DELETE http://localhost:3000/users/6
Content-Type: application/json