GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2Njg0MX0.WYm44BnZRrxKZ4G-GJU6NlWnW7l7GL_-6VOLWWSvC68
###
POST  http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2NTQ2MH0.Ljyd1L-yTfHTYv4tHDmmKW9xCLmLLXb8Jso55nsKIlM


{
    "name":"Monyet Ksnandar",
    "nim":"3434232",
    "image_profile":"fsdfede",
    "division": "Multimedia",
    "email": "gabriel@gmail.com",
    "number_phone": "0895622060619"
}

###
GET http://localhost:3000/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2NTQ2MH0.Ljyd1L-yTfHTYv4tHDmmKW9xCLmLLXb8Jso55nsKIlM


###
PUT  http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2NTQ2MH0.Ljyd1L-yTfHTYv4tHDmmKW9xCLmLLXb8Jso55nsKIlM

{
    "name":"Gabriel Yonathan",
    "nim":"3434232",
    "image_profile":"fsdfede",
    "division": "Multimedia",
    "email": "gabriel@gmail.com",
    "role": "admin",
    "number_phone": "0895622060619"
}

###
DELETE http://localhost:3000/users/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2NTQ2MH0.Ljyd1L-yTfHTYv4tHDmmKW9xCLmLLXb8Jso55nsKIlM
