GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo1LCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsQGdtYWlsLmNvbSIsImltYWdlX3Byb2ZpbGUiOiJmc2RmZWRlIiwiZGl2aXNpb24iOiJNdWx0aW1lZGlhIiwicm9sZSI6Im1lbnRvciIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk3NDU1NzM1fQ.ekseQ1TVPBh8Hp7XI4UC390Ts_NgoQYVnYoSU6aaU2o
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsbEBnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJhZG1pbiIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk3NDUzNzAyfQ.BQ2aWFlUHL10w0U7hriinlq9wlaLGdHHMnghG1JxkIU

###
POST  http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo1LCJuYW1lIjoiTW9ueWV0IERhbW0iLCJuaW0iOiIzNDM0MjMyIiwiZW1haWwiOiJnYWJyaWVsQGdtYWlsLmNvbSIsImltYWdlX3Byb2ZpbGUiOiJmc2RmZWRlIiwiZGl2aXNpb24iOiJNdWx0aW1lZGlhIiwicm9sZSI6Im1lbnRvciIsIm51bWJlcl9waG9uZSI6IjA4OTU2MjIwNjA2MTkifSwiaWF0IjoxNjk3NDU1NzM1fQ.ekseQ1TVPBh8Hp7XI4UC390Ts_NgoQYVnYoSU6aaU2o


{
    "name":"Monyet Ksnandar",
    "nim":"3434232",
    "image_profile":"fsdfede",
    "division": "Multimedia",
    "email": "gabriel@gmail.com",
    "number_phone": "0895622060619"
}

###
GET http://localhost:3000/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2NTQ2MH0.Ljyd1L-yTfHTYv4tHDmmKW9xCLmLLXb8Jso55nsKIlM


###
PUT  http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2NTQ2MH0.Ljyd1L-yTfHTYv4tHDmmKW9xCLmLLXb8Jso55nsKIlM

{
    "name":"Gabriel Yonathan",
    "nim":"3434232",
    "image_profile":"fsdfede",
    "division": "Multimedia",
    "email": "gabriel@gmail.com",
    "role": "admin",
    "number_phone": "0895622060619"
}

###
DELETE http://localhost:3000/users/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMywibmFtZSI6Ik1vbnlldCBEYW1tIiwibmltIjoiMzQzNDIzMiIsImVtYWlsIjoiZ0BnbWFpbC5jb20iLCJpbWFnZV9wcm9maWxlIjoiZnNkZmVkZSIsImRpdmlzaW9uIjoiTXVsdGltZWRpYSIsInJvbGUiOiJtZW50b3IiLCJudW1iZXJfcGhvbmUiOiIwODk1NjIyMDYwNjE5In0sImlhdCI6MTY5NzM2NTQ2MH0.Ljyd1L-yTfHTYv4tHDmmKW9xCLmLLXb8Jso55nsKIlM
